### ISSUE TITLE
Building attractive banner to dress out the map

### ISSUE THREAD

**Issue by fmichaelconway** [azgs/azwinemap#11]
Would it be possible to include a colored banner or banner with a photo collage to dress up the map a bit?  I’m sure Stephanie could design something nice, but if there is a re-sizing issue or difficulty in deploying, we should probably pass.

Mike

**Comment by jessicagood** [comment]
@fmichaelconway Sure, @skmar you can download the site from https://github.com/azgs/azwinemap with the Download Zip button and make the edits to the navbar yourself. There is nothing special about running this site, just use index.html like normal. 

The UI componets use Bootstrap. Here are docs on the [navbar](http://getbootstrap.com/components/#navbar) and I'm sure you can find many other sources as well. Another thing to note is that the site is responsive so whatever changes you make would need to work for small screens too. And I'd definitely take caution if you want to make the navbar any taller than it is now since it will take up a lot of real estate on a small screen. When you've made your edits @Lbookman or I can put them on the live site.

**Comment by skmar** [comment]
Closed with commit 40519e4
