### ISSUE TITLE
Directions from the middle of nowhere

### ISSUE THREAD

**Issue by ridavis** [azgs/azwinemap#5]
Please double check the directions code and make sure it is working properly.

**Comment by jessicagood** [comment]
From what I can tell this happens if there are ambiguities with the location you've entered. If there are ambiguities the Mapquest Directions API chooses the first location that matches the location entered by the user. For example, if I just enter 416 W Congress, the first result Mapquest gets is in Kansas but if I add Tucson or AZ then the ambiguity is eliminated and Mapquest finds location we actually want.

To help mitigate this problem I added a help button next to the location input box to show the user the proper ways to enter a location.

How's that look @ridavis?

**Comment by jessicagood** [comment]
@ridavis Can this issue be closed?

**Comment by ridavis** [comment]
I think so. It works OK to me.
